### ISSUE TITLE
method to run on multi-computers

### ISSUE THREAD

**Issue by amrhamedp** [rubenafo/docker-hadoop-cluster#1]
The tutorial as far as i see allow creating multinodes but all of them on single computer.
Did you try to build one using network of physical computers?

**Comment by rubenafo** [comment]
The main purpose of the tutorial is actually to replicate a physical network using docker and build a cluster on top of it. 
You can always ignore all the Docker setup and just execute the commands contained in the Dockerfiles in a shell script using ssh on your network machines.
