### ISSUE TITLE
Greetings ! Can you help with error on UNPROTECTED PRIVATE KEY FILE please?? 

### ISSUE THREAD

**Issue by rajabhathor** [rubenafo/docker-hadoop-cluster#11]
Greetings ! Can you help with error on UNPROTECTED PRIVATE KEY FILE please?? 

attaching error messages...

Thanks!
Regards
Raj
![private key file permission errors](https://user-images.githubusercontent.com/8761805/113089922-a26c1600-91b6-11eb-867d-7aaa0142d4be.PNG)
![private key file permission errors](https://user-images.githubusercontent.com/8761805/113089949-ae57d800-91b6-11eb-96d9-e162ff4aca95.PNG)
![image](https://user-images.githubusercontent.com/8761805/113089979-bdd72100-91b6-11eb-8c75-3b21b3e0eabc.png)

**Comment by rubenafo** [comment]
I think the permissions on your key files are too open (0755). I suggest trying assigning them less privileges (e.g, sudo chmod 600 ~/.ssh/id_rsa)  , https://www.howtogeek.com/168119/fixing-warning-unprotected-private-key-file-on-linux/
