### ISSUE TITLE
Network Sparknet not found (Possible rookie mistake)

### ISSUE THREAD

**Issue by combrinckd** [rubenafo/docker-hadoop-cluster#5]
I followed the steps laid out to get the cluster running. However the last step I keep getting network issues. What am I missing, where should the network be set up? 

*Must be a rookie issue :)*

Below output on bash when running *./cluster.sh deploy*

d0a34aebc25e
b275e68a1eb1
d396b6f66f84
5620e240a15c
Error: No such network: sparknet
Error response from daemon: could not find plugin bridge in v1 plugin registry: plugin not found
>> Starting nodes master and worker nodes ...
b3845db3e039c4b19f0fcf8c392d332e7ea14e5b5a4eb6163b9a22bf8ec5bfe4
docker: Error response from daemon: network sparknet not found.
3df880ee2c12782f63e25720b0766871cbcad450fde70aa7545162cd5ca39454
docker: Error response from daemon: network sparknet not found.
b209f7b1cbdfe5e58d995c7b8a5bb8bb7a8ade217609d5b9a9ff7ccc50794e46
docker: Error response from daemon: network sparknet not found.
e34b422b13a75a1693ef359fd451b42b09cc6db342182c8337446fdaa7f019b6
docker: Error response from daemon: network sparknet not found.
>> Formatting hdfs ...
Error response from daemon: Container b3845db3e039c4b19f0fcf8c392d332e7ea14e5b5a4eb6163b9a22bf8ec5bfe4 is not running
Error response from daemon: network sparknet not found
Error response from daemon: network sparknet not found
Error response from daemon: network sparknet not found
Error response from daemon: network sparknet not found
Error: failed to start containers: nodemaster, node2, node3, node4
>> Starting hdfs ...
Error response from daemon: Container b3845db3e039c4b19f0fcf8c392d332e7ea14e5b5a4eb6163b9a22bf8ec5bfe4 is not running
>> Starting yarn ...
Error response from daemon: Container b3845db3e039c4b19f0fcf8c392d332e7ea14e5b5a4eb6163b9a22bf8ec5bfe4 is not running
>> Starting Spark ...
Error response from daemon: Container b3845db3e039c4b19f0fcf8c392d332e7ea14e5b5a4eb6163b9a22bf8ec5bfe4 is not running
Error response from daemon: Container 3df880ee2c12782f63e25720b0766871cbcad450fde70aa7545162cd5ca39454 is not running
Error response from daemon: Container b209f7b1cbdfe5e58d995c7b8a5bb8bb7a8ade217609d5b9a9ff7ccc50794e46 is not running
Error response from daemon: Container e34b422b13a75a1693ef359fd451b42b09cc6db342182c8337446fdaa7f019b6 is not running
Hadoop info @ nodemaster: http://:8088/cluster
Spark info @ nodemater  : http://:8080/
DFS Health @ nodemaster : http://:9870/dfshealth.html

**Comment by rubenafo** [comment]
Hi, apparently it's a Windows 10 issue: https://github.com/docker/for-win/issues/1960
Is that your case?

**Comment by combrinckd** [comment]
Think it was Windows 10 issue yes.. Recently dual booted to Linux and ran without an issue for testing purposes.
